version: '3'
services:
  # web:
  #   build: .
  #   ports:
  #    - "5000:5000"
  #   volumes:
  #    - .:/code
  postgres:
    image: "nimbustech/postgres-ssl:9.5"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  redis:
    image: "bitnami/redis:latest"
    ports:
      - "6379:6379"
  yourprio:
    build: .
    depends_on:
      - redis
      - postgres
    ports:
      - "4242:4242"
      